config/routes.rb
SampleApp::Application.routes.draw do
  resources :users

  match '/signup', :to => 'users#new'

  match '/contact', :to => 'pages#contact' # pages/contact wont do
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  root :to => 'pages#home'

end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base
  attr_accessor :password  # creates a virtual password attribute
  attr_accessible :name, :email, :password, :password_confirmation

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i # / to indicate start and end of regex. i to indicate case-insensitivity

  validates :name, :presence => true, :length => {:maximum => 50}
  validates :email, :presence => true,
                    :format => {:with => email_regex},
                    :uniqueness => {:case_sensitive => false}
  # Automatically create the virtual attribute 'password_confirmation'
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => {:within => 6..40}

  before_save :encrypt_password # register a callback before save

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  private

    def encrypt_password
      self.salt = make_salt if new_record? # to make sure that when the record is being updated the salt is not changed
      self.encrypted_password = encrypt(password) # self required otherwise local var will be created. self is optional
                                                  # on RHS
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact Us"
  end

  def about
    @title = "About"
  end

  def help
    @title = "Help"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @title = "Sign up"
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer style="text-align: center; margin-top: 10px;">
  <nav class="round">

      <%= link_to "About", about_path %> &nbsp;
      <%= link_to "Contact", contact_path %> &nbsp;
      <a href="http://news.railstutorial.org/">News</a> &nbsp;
      <a href="http://www.railstutorial.org/">Rails Tutorial</a>

  </nav>
</footer>

app/views/layouts/_header.html.erb
<header style="padding: 1em;">
  <nav class="round" style="float: right;">

      <%= link_to "Home", root_path %> &nbsp;
      <%= link_to "Help", help_path %> &nbsp;
      <%= link_to "Sign In", '#' %>

  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title> <!-- Rest of it is taken care of in application_helper.rb file-->
  <%= csrf_meta_tag %> <!-- Prevents cross-site request forgery -->
</head>
<body>
<div class="container">
    <%= render 'layouts/header' %> <!-- partial -->
    <section class="round">
        <!-- inserts the content of each pae into the layout. meaning using this layout ensures that  visiting the page
            /pages/home converts the contents of the file to HTML and inserts it in place of  the below stmt-->
        <%= yield %>
    </section>
    <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/feedback">feedback page</a>.
</p>

app/views/pages/help.html.erb
<h1>Help</h1>

app/views/pages/home.html.erb
<h1>Sample App</h1>
<p>
  This is the home page for the <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a> sample application.
</p>

<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<table class="profile" summary="profile information">
  <tr>
    <td class="main">
      <h1>
        <%= @user.name %>
      </h1>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.name %><br/>
      <strong>URL</strong>  <%= link_to user_path(@user), @user %>
    </td>
  </tr>
</table>